- name: Install RPM repo config of PostgreSQL
  yum:
    name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
    state: installed

- name: Install PostgreSQL Client/Server
  yum:
    name:
      - postgresql15
      - postgresql15-server
    state: installed

- name: Initialize PostgreSQL data directory
  shell: '/usr/bin/env PGSETUP_INITDB_OPTIONS="-E UTF-8 --locale=en_US.UTF8 -k" /usr/pgsql-15/bin/postgresql-15-setup initdb'
  args:
    creates: /var/lib/pgsql/15/data/postgresql.conf

- name: Update pg_hba.conf
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/15/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0644

- name: Enable PostgreSQL Server
  systemd:
    name: postgresql-15.service
    enabled: true
    state: started
